Repository codemaniac-sahil/quiz-using-c, pull requests merged in 2022-10, with the labels that each got.

#1 Quiz
  quiz.c
Labels: enhancement, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#2 one more c language question is added
  quiz.c
  quiz.exe
Labels: enhancement, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#5 Added Que No.7
  quiz.c
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#7 Added 9th question in code
  quiz.c
Labels: good first issue, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#12 updated the questions and added question 14
  quiz.c
Labels: good first issue, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#13 Fixed the minor bugs and added Ques15
  quiz.c
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted
